/**
 * Build a rendered Markdown document from fan-in upstream payloads.
 */

/**
 * @param {string} s
 */
export function slugify(s) {
  return (
    String(s)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "") || "report"
  );
}

/**
 * @param {string} text
 */
function escapeMarkdownInline(text) {
  return text.replace(/([\\`*_[\]])/g, "\\$1");
}

/**
 * @param {string} text
 */
function formatBodyAsMarkdown(text) {
  const normalized = text.replace(/\r\n/g, "\n").replace(/\t/g, " ").trim();
  if (!normalized) return "_(no text extracted)_\n";

  const paragraphs = normalized
    .split(/\n{2,}/)
    .map((p) => p.replace(/\n/g, " ").replace(/\s+/g, " ").trim())
    .filter(Boolean);

  return paragraphs
    .map((p) => {
      const safe = escapeMarkdownInline(p);
      return safe.length > 500 ? safe.slice(0, 500) + "…" : safe;
    })
    .join("\n\n");
}

/**
 * @param {unknown} item
 * @param {number} index
 */
export function normalizeSource(item, index) {
  if (item === null || item === undefined) {
    return {
      index: index + 1,
      slug: `source-${index + 1}`,
      heading: `Source ${index + 1}`,
      url: null,
      status: null,
      title: null,
      label: null,
      text: "",
      truncated: false,
    };
  }

  if (typeof item === "string") {
    return {
      index: index + 1,
      slug: `source-${index + 1}`,
      heading: `Source ${index + 1}`,
      url: null,
      status: null,
      title: null,
      label: null,
      text: item,
      truncated: false,
    };
  }

  if (typeof item === "object") {
    const o = /** @type {Record<string, unknown>} */ (item);
    const label = typeof o.label === "string" ? o.label : null;
    const title = typeof o.title === "string" ? o.title : null;
    const url = typeof o.url === "string" ? o.url : null;
    const heading = label ?? title ?? url ?? `Source ${index + 1}`;
    return {
      index: index + 1,
      slug: slugify(heading),
      heading,
      url,
      status: o.status ?? null,
      title,
      label,
      text:
        typeof o.text === "string"
          ? o.text
          : typeof o.markdown === "string"
            ? o.markdown
            : JSON.stringify(o, null, 2),
      truncated: Boolean(o.truncated),
      contentType: o.contentType ?? null,
      finalUrl: o.finalUrl ?? null,
    };
  }

  return {
    index: index + 1,
    slug: `source-${index + 1}`,
    heading: `Source ${index + 1}`,
    url: null,
    status: null,
    title: null,
    label: null,
    text: JSON.stringify(item, null, 2),
    truncated: false,
  };
}

/**
 * @param {ReturnType<typeof normalizeSource>[]} sources
 * @param {{ title: string, intro: string, generatedAt: string }} meta
 */
export function renderMarkdownReport(sources, meta) {
  const lines = [];

  lines.push("---");
  lines.push(`title: ${JSON.stringify(meta.title)}`);
  lines.push(`generatedAt: ${meta.generatedAt}`);
  lines.push(`sourceCount: ${sources.length}`);
  lines.push("---");
  lines.push("");
  lines.push(`# ${meta.title}`);
  lines.push("");
  if (meta.intro) {
    lines.push(meta.intro.trim());
    lines.push("");
  }

  lines.push("## Table of contents");
  lines.push("");
  for (const s of sources) {
    lines.push(`${s.index}. [${s.heading}](#${s.index}-${s.slug})`);
  }
  lines.push("");

  for (const s of sources) {
    lines.push("---");
    lines.push("");
    lines.push(`## ${s.index}. ${s.heading} {#${s.index}-${s.slug}}`);
    lines.push("");
    lines.push("| Field | Value |");
    lines.push("| --- | --- |");
    if (s.label) lines.push(`| Label | ${s.label} |`);
    if (s.url) lines.push(`| URL | <${s.url}> |`);
    if (s.finalUrl && s.finalUrl !== s.url) {
      lines.push(`| Final URL | <${s.finalUrl}> |`);
    }
    if (s.status != null) lines.push(`| HTTP status | ${s.status} |`);
    if (s.contentType) lines.push(`| Content-Type | ${s.contentType} |`);
    if (s.truncated) lines.push("| Truncated | yes |");
    lines.push("");
    lines.push("### Page content");
    lines.push("");
    lines.push(formatBodyAsMarkdown(s.text));
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push("_Report generated by arc-dag `markdownOutput` node._");
  lines.push("");

  return lines.join("\n");
}
